import type { DiffSet } from '@/git/diff';
import { describeTarget } from '@/review/prompts';
import type { ReviewResult, Severity } from '@/review/schema';

const SEVERITY_EMOJI: Record<Severity, string> = {
  critical: '⛔',
  major: '🔴',
  minor: '🟡',
  suggestion: '🔵',
  info: '⚪',
};

// A self-contained markdown report: `ergo review --format markdown > review.md`.
export function renderMarkdown(review: ReviewResult, diff: DiffSet): string {
  const { summary, findings, stats } = review;
  const md: string[] = [];

  md.push(`# ergo review`);
  md.push('');
  md.push(
    `> ${describeTarget(diff)} · ${stats.filesReviewed} file(s) · +${stats.additions}/-${stats.deletions}`,
  );
  md.push('');

  if (summary.summary) {
    md.push('## Summary');
    md.push('');
    md.push(summary.summary);
    md.push('');
  }

  if (summary.fileSummaries.length > 0) {
    md.push('## Changed files');
    md.push('');
    md.push('| File | Change |');
    md.push('| --- | --- |');
    for (const f of summary.fileSummaries) {
      md.push(`| \`${f.path}\` | ${f.summary.replace(/\|/g, '\\|')} |`);
    }
    md.push('');
  }

  if (summary.walkthrough) {
    md.push('## Walkthrough');
    md.push('');
    md.push(summary.walkthrough);
    md.push('');
  }

  if (summary.sequenceDiagram?.trim()) {
    md.push('## Sequence diagram');
    md.push('');
    md.push('```mermaid');
    md.push(summary.sequenceDiagram.trim());
    md.push('```');
    md.push('');
  }

  md.push('## Findings');
  md.push('');
  if (findings.length === 0) {
    md.push('✅ No issues found.');
    md.push('');
  } else {
    for (const f of findings) {
      const loc =
        f.startLine === f.endLine
          ? `${f.file}:${f.startLine}`
          : `${f.file}:${f.startLine}-${f.endLine}`;
      md.push(
        `### ${SEVERITY_EMOJI[f.severity]} ${f.title} \`${f.severity}\` \`${f.category}\``,
      );
      md.push('');
      md.push(`- **Location:** \`${loc}\``);
      md.push(`- **Confidence:** ${f.confidence.toFixed(2)} · **ID:** ${f.id}`);
      md.push('');
      md.push(f.description);
      if (f.rationale && f.rationale !== f.description) {
        md.push('');
        md.push(`_${f.rationale}_`);
      }
      if (f.suggestedPatch?.trim()) {
        md.push('');
        md.push('**Suggested fix:**');
        md.push('');
        md.push('```');
        md.push(f.suggestedPatch.trimEnd());
        md.push('```');
      }
      md.push('');
    }
  }

  md.push('---');
  const cost = stats.subscriptionCovered
    ? 'subscription (no API cost)'
    : stats.costUsd !== undefined
      ? `$${stats.costUsd.toFixed(4)}`
      : 'n/a';
  md.push(
    `<sub>model ${stats.model} (${stats.provider}) · ${stats.tokensInput}→${stats.tokensOutput} tokens · ${cost} · ${(stats.durationMs / 1000).toFixed(1)}s · generated by [ergo](https://github.com/o1x3/ergo)</sub>`,
  );
  md.push('');
  return md.join('\n');
}
